const BASE_URL = process.env.REACT_APP_API_BASE_URL;

const ENDPOINTS = {
  USER_MULTICLIENT: `${BASE_URL}/UsuarioMulticliente/`,
  BALANCE_PARAMETERS: `${BASE_URL}/ParametroBalanceGeneral/padre`,
  BALANCE_PARAMETERS_ID: `${BASE_URL}/ParametroBalanceGeneral/`,
  BALANCE_SHEET: `${BASE_URL}/BalanceGeneral/Encabezado`,
  BALANCE_SHEET_CHILD: `${BASE_URL}/BalanceGeneral/SubEncabezado`,
  BALANCE_SHEET_DETAIL: `${BASE_URL}/BalanceGeneral/Detalle`,
  BALANCE_SHEET_THIRD: `${BASE_URL}/BalanceGeneral/Tercero`,
  BALANCE_SHEET_YEAR: `${BASE_URL}/BalanceGeneral/anios`,
  BALANCE_SHEET_DOWNLOAD_EXCEL: `${BASE_URL}/BalanceGeneral/Descargar/Excel`,
  BALANCE_SHEET_DOWNLOAD_EXCEL_YEAR: `${BASE_URL}/BalanceGeneral/Descargar/ExcelAgrupado`,
  BALANCE_LANGUAGE_MONTH: `${BASE_URL}/Meses/`,
  BALANCE_SHEET_GROUPED_HEADER: `${BASE_URL}/BalanceGeneral/EncabezadoAgrupado`,
  BALANCE_SHEET_GROUPED_CHILD: `${BASE_URL}/BalanceGeneral/SubEncabezadoAgrupado`,
  BANK_PARAMETERS_ID: `${BASE_URL}/Banco/`,
  ACCOUNT_TYPE: `${BASE_URL}/TipoCuenta/`,
  THRID_PARTY: `${BASE_URL}/ParametroTercero/`,
  PAID_PROGRAMMER: `${BASE_URL}/ProgramadorPago/Consultar`,
  PAID_PROGRAMMER_CSV: `${BASE_URL}/ProgramadorPago/GenerarCSV`,
  BALANCE_SHEET_GROUPED_DETAIL: `${BASE_URL}/BalanceGeneral/DetalleAgrupado`,
  BALANCE_SHEET_GROUPED_THIRD: `${BASE_URL}/BalanceGeneral/TerceroAgrupado`,
  BALANCE_SHEET_SAVENOTE: `${BASE_URL}/BalanceGeneral/GuardarNota`,
  CLIENT_LOGO: `${BASE_URL}/ClienteLogo`,
  CLIENT_LOGO_SAVE: `${BASE_URL}/ClienteLogo/Guardar`,
  CASH_BOX_HEADER: `${BASE_URL}/FlujoCaja/Encabezado`,
  CASH_BOX_SUBHEADER: `${BASE_URL}/FlujoCaja/SubEncabezado`,
  CASH_BOX_THIRD: `${BASE_URL}/FlujoCaja/DetalleTercero`,
  CASH_BOX_LISTTHIRD: `${BASE_URL}/FlujoCaja/ListarTercero`,
  CASH_BOX_DOWNLOAD_EXCEL: `${BASE_URL}/FlujoCaja/DescargarExcel`,
  SEND_EXCEL: `${BASE_URL}/BalanceGeneral/EnviarExcel`,
  SEND_EXCEL_CASH_BOX: `${BASE_URL}/FlujoCaja/EnviarExcel`,
  SEND_MAIL: `${BASE_URL}/Mail`,
  PYG_GRUPOS: `${BASE_URL}/PYG/consultarPYGGrupos`,
  PYG_CUENTAS: `${BASE_URL}/PYG/consultarPYGCuentas`,
  PYG_SUBCUENTAS: `${BASE_URL}/PYG/ConsultarPYGSubCuentas`,
  PYG_AUXILIAR: `${BASE_URL}/PYG/consultarPYGAuxiliar`,
  PYG_SHEET_DOWNLOAD_EXCEL: `${BASE_URL}/PYG/Descargar/PYGExcel`,
  PYG_SHEET_SEND_EXCEL: `${BASE_URL}/PYG/Enviar/PYGExcel`,
};

export default ENDPOINTS;
